### ISSUE TITLE
 atomicalsir &  atomicalsir.js

### ISSUE THREAD

**Issue by agarwood777** [hack-ink/atomicalsir#21]
I cannot start atomicalsir normally. Should the two programs be used separately or together?
![atomicalsir 2024-01-03 112231](https://github.com/hack-ink/atomicalsir/assets/83913710/1d19da62-b391-413a-a97e-3b892e465ad6)

**Comment by thoo2** [comment]
![Screenshot 2024-01-07 214618](https://github.com/hack-ink/atomicalsir/assets/85311037/d8910864-5e30-4462-a40a-6e8196e3a741)
Sir ,this version only for minted quark?

**Comment by AurevoirXavier** [comment]
> Sir ,this version only for minted quark?

rust-engine would fix these.
Please wait for #17.
