### ISSUE TITLE
rust engine

### ISSUE THREAD

**Issue by 9840144** [hack-ink/atomicalsir#23]
./atomicalsir --rust-engine ./wallets --ticker dragon
Can I mine dragon using the rust engine? I tried it and found a solution, but I couldn't commit

**Comment by AurevoirXavier** [comment]
> ./atomicalsir --rust-engine ./wallets --ticker dragon Can I mine dragon using the rust engine? I tried it and found a solution, but I couldn't commit

Yep, that's why it remains a pull request. I'll finish it later.
