### ISSUE TITLE
Mint not recognized as atomicals

### ISSUE THREAD

**Issue by Mitochondria7** [hack-ink/atomicalsir#27]
I just did a test using latest code (0.1.9) . The mint is very fast, however, after confirmation on chain, it seems the atomicals index didn't recognize the successful mint received in primary wallet as atomicals. It considers it as normal UTXO. How can I fix this? Thanks

**Comment by AurevoirXavier** [comment]
> I just did a test using latest code (0.1.9) . The mint is very fast, however, after confirmation on chain, it seems the atomicals index didn't recognize the successful mint received in primary wallet as atomicals. It considers it as normal UTXO. How can I fix this? Thanks

What command are you using?

**Comment by Mitochondria7** [comment]
> Which command are you using? It currently doesn't support certain special tokens e.g. which requires bitworkr.
what do you mean by bitworkr? bitwork for realm?

I was testing it on sophon, which is a token that has same bitwork difficulty as quark. Here is my command: atomicalsir --ticker sophon --max-fee 40 --rust-engine /my atomical-JS wallet path. 

The tx id is: 000000adc70f392c8710bb292cfe17c54a23a88f8d4129631a3e13ad6348de53, you could see reveal tx seems to be successfully delivered. but that was considered as regular UTXO when I check my address balance

**Comment by star8ks** [comment]
> I was testing it on sophon, which is a token that has same bitwork difficulty as quark. Here is my command: atomicalsir --ticker sophon --max-fee 40 --rust-engine /my atomical-JS wallet path.
> 
> The tx id is: 000000adc70f392c8710bb292cfe17c54a23a88f8d4129631a3e13ad6348de53, you could see reveal tx seems to be successfully delivered. but that was considered as regular UTXO when I check my address balance

Sophon's reveal tx should be started with "6238", but rust-engine does not support bitworkr currently.

**Comment by Mitochondria7** [comment]
> > I was testing it on sophon, which is a token that has same bitwork difficulty as quark. Here is my command: atomicalsir --ticker sophon --max-fee 40 --rust-engine /my atomical-JS wallet path.
> > The tx id is: 000000adc70f392c8710bb292cfe17c54a23a88f8d4129631a3e13ad6348de53, you could see reveal tx seems to be successfully delivered. but that was considered as regular UTXO when I check my address balance
> 
> Bitworkr of sophon is "6238", but rust-engine does not support bitworkr currently.

Thanks for the explanation! this might be a dumb question, bitworkr stands for reveal bitwork? I didn't realize it exist previously. Just did some quick search, indeed quark didn't require bitworkr, then it make senses that rust-engine can work on it.

**Comment by star8ks** [comment]
> bitworkr stands for reveal bitwork?

Yes.

**Comment by AurevoirXavier** [comment]
I will add bitworkr feature later.
