### ISSUE TITLE
Run rust engine failed

### ISSUE THREAD

**Issue by yujianFresh** [hack-ink/atomicalsir#32]
Hi:
 the code run failed. result is :
<img width="1399" alt="截屏2024-01-13 15 28 06" src="https://github.com/hack-ink/atomicalsir/assets/24457810/da0c88b0-c6be-4705-ab1c-447593d9751b">

**Comment by AurevoirXavier** [comment]
Enable logging to view detailed information: `RUST_LOG=atomicalsir=debug`

```
{"success": false, "code": -32603, "message": "Internal server error."}
```

Consider running a ElectrumX server yourself.
