### ISSUE TITLE
Missing OP_RETURN transactions, fund stuck?

### ISSUE THREAD

**Issue by Gigatron** [hack-ink/atomicalsir#47]
Hi, pelase take a look at my following minting transactions.

https://mempool.space/address/bc1p9ujws0663hllhu9yr4j8ee3cj5p4f6k3sg4d8jh59mpz8y223t4qufzp3r
https://mempool.space/address/bc1pfejlwrm9rlldy237q2ff3jtwvp7llrlge9rxze4xekustnzenq8qnfrhv5

I believe there should be a second transaction with `OP_RETURN` tags but it seems they never happened. Is there a way to recover the fund?

**Comment by AurevoirXavier** [comment]
I guess this is the same as #44.

**Comment by Gigatron** [comment]
Here are more logs:
```
Success sent tx:  0000000a033a2cc5460812433ce3d0366b4ed000df45fe85d1bd91481a129586
Workers have completed their tasks.
...
...
...
...
...
Detected Funding UTXO (0000000a033a2cc5460812433ce3d0366b4ed000df45fe85d1bd91481a129586:0) with value 110785 for funding...

Atomicals Bitwork Mining - Requested bitwork proof-of-work mining for the reveal transaction.
bitworkr (input): 6238
bitworkr (decoded): 6238
---------
WARNING: This might take a very long time depending on the speed of the CPU.
Time to mine estimates:
- prefix length <= 4: about a minute or two. ~65,536 hashes on average.
- prefix length 5: several minutes. ~1,048,576 hashes on average.
- prefix length 6: up to an hour or more. ~16,777,216 hashes on average.
- prefix length >= 7: a few hours or much longer. >268,435,456 hashes on average.

Starting mining now...

Generated nonces:  0 , time:  1705608069
Generated nonces:  10000 , time:  1705608075
Generated nonces:  20000 , time:  1705608081
{
  "success": false,
  "message": "TypeError: process.stdout.clearLine is not a function",
  "error": {}
}
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

I think it got interrupted somehow, so it's not entirely same as #44.

**Comment by AurevoirXavier** [comment]
It seems you're using the JS engine. If that's the case, this issue should be reported to atomicals-js rather than atomicalsir.

**Comment by AurevoirXavier** [comment]
- https://github.com/atomicals/atomicals-js/pull/154
- https://github.com/atomicals/atomicals-js/pull/136
- https://github.com/atomicals/atomicals-js/issues/90

**Comment by Gigatron** [comment]
Yes, I'm running the js engine. But running atomicals-js code directly without using atomicalsir just works fine. But when I tried to run atomicalsir with atomicals-js,  the issue just happens. Therefore I suspect the root cause is probably relevant to how atomicalsir is invoking atomicals-js and parsing the results.

**Comment by AurevoirXavier** [comment]
Does this happen every time?

I guess it's because the atomicalsir loop runs atomicals-js.

**Comment by Gigatron** [comment]
It happend two times in a row before I stopped the script to avoid losing more fund. So I'm not exactly sure if it always happens. Maybe you can verify the behavior on the testnet.

**Comment by AurevoirXavier** [comment]
> It happend two times in a row before I stopped the script to avoid losing more fund. So I'm not exactly sure if it always happens. Maybe you can verify the behavior on the testnet.

What's your platform/OS? atomticals-js version? atomicalsir version?

I'm 80% sure https://github.com/atomicals/atomicals-js/pull/136 can fix this.

**Comment by Gigatron** [comment]
OS:
NAME="Fedora Linux"
VERSION="38 (Cloud Edition)"

commit dbb5c439220842d7a44cbb924fab72aa95c8e4d8 for atomticals-js 
and 
commit 8c77436fe094dfd87ad61bb03d98cd8718c54ec6 for atomicalsir
