### ISSUE TITLE
Can not parse wallet jason

### ISSUE THREAD

**Issue by JelloHuang** [hack-ink/atomicalsir#60]
version: atomicalsir 0.2.0-3fd3e3b-x86_64-unknown-linux-gnu
./atomicalsir --rust-engine ./wallets --fee-bound 33,38 --ticker btcsoul
ERROR atomicals_electrumx: failed to parse response into JSON due to error decoding response body: missing field response at line 1 column 129

pls clone the new project and build test

**Comment by JelloHuang** [comment]
BTW:what is the difference between js-engine and rust-engine.

js-engine mean network transfer use js and mining use rust algo?

**Comment by AurevoirXavier** [comment]
Dup of #32.

**Comment by AurevoirXavier** [comment]
> BTW:what is the difference between js-engine and rust-engine.
> 
> js-engine mean network transfer use js and mining use rust algo?

`js-engine` uses atomicals-js for mining.
`rust-engine` uses atomicalsir native miner.
