### ISSUE TITLE
Can't excute mining program

### ISSUE THREAD

**Issue by GeorgeLyu6** [hack-ink/atomicalsir#8]
![image](https://github.com/hack-ink/atomicalsir/assets/130268508/5cec349c-f9e2-466b-9d45-baf80a429742)

it seem to be a loop to find gas fee, rather than the mining program

**Comment by AurevoirXavier** [comment]
It skips mining due to certain issues, the most prevalent being an unavailable electrumx server. Please review the `stdout.log` file for more information.

Consider using the latest version for a more detailed log in `atomicalsir` ouptut.

**Comment by GeorgeLyu6** [comment]
Ur right, sir. Thank u!
